### ISSUE TITLE
singularity error

### ISSUE THREAD

**Issue by polya18** [KosinskiLab/AlphaPulldown#344]
When i run singularity exec, it reported fatal error.
`singularity exec --no-home --bind /media/lenv/alphaIP_out:/mnt /media/lenv/alphaIP_out/alpha-analysis_jax_0.4.sif run_get_good_pae.sh --output_dir=/mnt --cutoff=10`
The error is "alpha-analysis_jax_0.4.sif: image format not recognized"
I used conda env for AlphaPulldown and singularity.
Would you please help me to figure it out?

**Comment by polya18** [comment]
That make sense. Thank you. It did not have any output and suggested me to increase cutoff number. How large does it accept for common Protein-Protein Interaction?

**Comment by dingquanyu** [comment]
Glad it helped! Perhaps you could try 100 first just to make every single model of yours pass the cutoff.

**Comment by polya18** [comment]
I tried a cutoff of 100, but it still didn't work. It reported "protein.pkl does not have ranking_debug.json. Skipped." Does that matter?

**Comment by krafie** [comment]
Heya, did you find a fix for this? I am having the same issue. It can't find "hits" even with a cut-off of 100. It also skips as no associated ranking_debug.json is found. Any help is appreciated.

Cheers,
K

**Comment by dingquanyu** [comment]
> I tried a cutoff of 100, but it still didn't work. It reported "protein.pkl does not have ranking_debug.json. Skipped." Does that matter?

@polya18 
It looks like you have mounted the wrong directory and the programme failed to find any sub directories in which ranking_debug.json and necessary pdb files exist.

**Comment by dingquanyu** [comment]
> Heya, did you find a fix for this? I am having the same issue. It can't find "hits" even with a cut-off of 100. It also skips as no associated ranking_debug.json is found. Any help is appreciated.
> 
> Cheers, K

Hi @krafie 
As the printed statement suggests, the folder does not contain ranking_debug.json and will skip it. A missing ranking_debug.json suggests unfinished or crashed modelling job. Alternatively, you might have mounted a wrong directory.

Yours
Dingquan

**Comment by krafie** [comment]
> > Heya, did you find a fix for this? I am having the same issue. It can't find "hits" even with a cut-off of 100. It also skips as no associated ranking_debug.json is found. Any help is appreciated.
> > Cheers, K
> 
> Hi @krafie As the printed statement suggests, the folder does not contain ranking_debug.json and will skip it. A missing ranking_debug.json suggests unfinished or crashed modelling job. Alternatively, you might have mounted a wrong directory.
> 
> Yours Dingquan

Hi Dingquan,

thanks for the quick response. I'll look into it again and hope to figure out where it went wrong.

All the best,
Karim

**Comment by dingquanyu** [comment]
Hi @B0r1sD 

Thanks for reporting the issue. Could you check whether you got the predictions_with_good_inter_pae.csv in the end?  

Yours
Dingquan

**Comment by B0r1sD** [comment]
Hello @dingquanyu

I did not. I checked both the directory I'm working in, the output directory I mounted, and did a `find` on my whole system. Only place I didn't check is in the container itself. But as it indicated having no scores below cutoff, I didn't bother. Is that expected behaviour, that the `predictions_with_good_inter_pae.csv` can still be found even with no hits?

**Comment by dingquanyu** [comment]
> Hello @dingquanyu
> 
> I did not. I checked both the directory I'm working in, the output directory I mounted, and did a `find` on my whole system. Only place I didn't check is in the container itself. But as it indicated having no scores below cutoff, I didn't bother. Is that expected behaviour, that the `predictions_with_good_inter_pae.csv` can still be found even with no hits?

I see. This file is not supposed to be created in this case. I'm just checking if the unexpected file was somehow created unexpectedly. I will look into this issue.

**Comment by maxvdb-dev** [comment]
I had the same issue and I found a fix. In the main function of 'get_good_inter_pae.py' there is a line: if "iptm" in data.keys() and "iptm+ptm" in data.keys():
However, ranking_debug.json files only have a "iptm+ptm" dictionary, so by removing the '"iptm" in data.keys() and' part it worked fine. In my case I was interested in all the outputs not only in the ones with a 'good' PAE. So if you need that aswell, you can also deactivate:
                # check = examine_inter_pae(
                    # pae_mtx, seq_lengths, cutoff=FLAGS.cutoff)
And remove the 'if check' line. It is important though that you rebuild the Apptainer container/image after making changes to the python script as the build uses the static version of the script after it has been build.

**Comment by dingquanyu** [comment]
@maxvdb-dev thanks a lot for the advice and tips! You could also just turn the ```and``` into ```or```in this line. https://github.com/KosinskiLab/AlphaPulldown/blob/29682ab83c8c5aa0e19d54c48b61883730143435/alphapulldown/analysis_pipeline/get_good_inter_pae.py#L127  I will fix this problem later.

**Comment by dingquanyu** [comment]
Hi @maxvdb-dev and @B0r1sD 

I have updated the singularity image in this PR #361 . Could you re-download it from: https://www.embl-hamburg.de/AlphaPulldown/downloads/alpha-analysis_jax_0.4.sif and try again? I believe it should work now.

Yours
Dingquan

**Comment by B0r1sD** [comment]
Hey @dingquanyu 
I've tried it again with the updated .sif file you linked (file size is 8 kB less so I know it was changed). Unfortunately, it has not changed anything it seems like, as I still don't get output (no CSV) when using the valid output from example 1. 

Anything I can provide to make your debugging easier? And on which data did you test it exactly; I only find https://github.com/KosinskiLab/AlphaPulldown/tree/main/test/test_data/P0DPR3_and_P0DPR3 as shared test data which I tried but also does not give a CSV file:
```sh
Unfortunately, none of your protein models had at least one PAE on the interface below your cutoff value : 10.0.
```

**Comment by dingquanyu** [comment]
Hi @B0r1sD 

Sorry I meant the examples from the baits.txt and candidates.txt. Here are the protein pairs I have tested: 

```
P78344;P08240
P78344;Q14240
P78344;P62945
P78344;O76094
P78344;P23588
P78344;P09132
P78344;P22090
P78344;P46778
P78344;P46781
P78344;P60842
P78344;P61011
P78344;Q9NX20
P78344;Q9Y5M8
```
and here's what I got:

| jobs              | iptm_ptm            | iptm       | pDockQ/mpDockQ      | average_interface_pae | average_interface_plddt | binding_energy      | interface | Num_intf_residues | Polar | Hydrophobic | Charged | contact_pairs | sc    | hb  | sb  | int_solv_en | int_area | pi_score |
| ----------------- | ------------------- | ---------- | ------------------- | --------------------- | ----------------------- | ------------------- | --------- | ----------------- | ----- | ----------- | ------- | ------------- | ----- | --- | --- | ----------- | -------- | -------- |
| P78344_and_P60842 | 0.8073141777145266  | 0.85734236 | 0.6216370121365561  | 7.164437719753811     | 73.72813370473541       | -13852.26395926436  | B_C       | 67                | 0.239 | 0.269       | 0.299   | 59            | 0.522 | 23  | 32  | -9.48       | 3384.44  | 1.21     |
| P78344_and_Q14240 | 0.7565451762167229  | 0.810629   | 0.6496131321314101  | 10.689969138294433    | 75.9755367231638        | -11850.808590485196 | B_C       | 94                | 0.213 | 0.287       | 0.362   | 108           | 0.514 | 35  | 39  | -8.13       | 3537.5   | 0.89     |
| P78344_and_P62945 | 0.6290067873741413  | 0.671387   | 0.06515304551943633 | 17.472288744790212    | 34.442784810126575      | -24469.558976366974 | B_C       | 15                | 0.333 | 0.133       | 0.533   | 18            | 0.365 | 2   | 19  | 2.23        | 1212.56  | -0.33    |
| P78344_and_P09132 | 0.6211262691675556  | 0.6589203  | 0.08134475366649119 | 10.510612529080088    | 66.92890109890108       | -28394.159764210377 | B_C       | 9                 | 0.111 | 0.556       | 0.333   | 6             | 0.388 | 7   | 13  | 3.48        | 765.08   | -0.49    |
| P78344_and_P22090 | 0.5515223939913818  | 0.59033155 | 0.14460282477765915 | 20.55140308838386     | 58.60125000000003       | -15654.731419052754 | B_C       | 27                | 0.296 | 0.259       | 0.407   | 30            | 0.418 | 8   | 11  | -0.2        | 1471.83  | -0.87    |
| P78344_and_O76094 | 0.5169412161606898  | 0.5467848  | 0.2130915592329316  | 23.06159787928253     | 45.59938144329897       | -65640.10889856739  | B_C       | 139               | 0.309 | 0.252       | 0.288   | 218           | 0.226 | 46  | 11  | -31.67      | 4363.1   | 0.56     |
| P78344_and_Q9NX20 | 0.36620426396535577 | 0.35568807 | 0.20392021331888244 | 19.932819245505506    | 63.48367816091956       | -34954.06917864921  | B_C       | 46                | 0.239 | 0.217       | 0.326   | 69            | 0.095 | 15  | 10  | -2.43       | 1540.74  | -0.77    |
| P78344_and_P23588 | 0.34902449646950484 | 0.34881938 | 0.1385904745097395  | 15.125836796890884    | 43.50447826086955       | -24956.307968167053 | B_C       | 50                | 0.3   | 0.4         | 0.2     | 51            | 0.521 | 9   | 9   | -23.48      | 2401.89  | 1.28     |
| P78344_and_P61011 | 0.33512340677145236 | 0.32496715 | 0.3353651779084972  | 25.146222874294363    | 60.29734693877547       | -23965.434001309848 | B_C       | 85                | 0.294 | 0.388       | 0.118   | 133           | 0.194 | 17  | 5   | -10.47      | 2421.55  | 0.57     |
| P78344_and_P08240 | 0.21724664073114736 | 0.18381809 | 0.31321204279729065 | 28.314014073117495    | 62.73298113207545       | -110237.89718595374 | B_C       | 63                | 0.222 | 0.365       | 0.317   | 86            | 0.191 | 14  | 9   | -6.76       | 2537.77  | -0.49    |
| P78344_and_Q9Y5M8 | 0.22085763865889452 | 0.1837084  | 0.4620402338477464  | 26.252773164644122    | 76.23718309859156       | -50507.42865413394  | B_C       | 53                | 0.189 | 0.377       | 0.34    | 78            | 0.079 | 17  | 4   | -7.3        | 1403.33  | -0.22    |

Perhaps you could try again but use a cutoff value of 100? 
Yours
Dingquan

**Comment by B0r1sD** [comment]
> Hi @B0r1sD
> 
> Sorry I meant the examples from the baits.txt and candidates.txt. Here are the protein pairs I have tested:
> 
> ```
> P78344;P08240
> P78344;Q14240
> P78344;P62945
> P78344;O76094
> P78344;P23588
> P78344;P09132
> P78344;P22090
> P78344;P46778
> P78344;P46781
> P78344;P60842
> P78344;P61011
> P78344;Q9NX20
> P78344;Q9Y5M8
> ```
> 
> and here's what I got:
> jobs 	iptm_ptm 	iptm 	pDockQ/mpDockQ 	average_interface_pae 	average_interface_plddt 	binding_energy 	interface 	Num_intf_residues 	Polar 	Hydrophobic 	Charged 	contact_pairs 	sc 	hb 	sb 	int_solv_en 	int_area 	pi_score
> P78344_and_P60842 	0.8073141777145266 	0.85734236 	0.6216370121365561 	7.164437719753811 	73.72813370473541 	-13852.26395926436 	B_C 	67 	0.239 	0.269 	0.299 	59 	0.522 	23 	32 	-9.48 	3384.44 	1.21
> P78344_and_Q14240 	0.7565451762167229 	0.810629 	0.6496131321314101 	10.689969138294433 	75.9755367231638 	-11850.808590485196 	B_C 	94 	0.213 	0.287 	0.362 	108 	0.514 	35 	39 	-8.13 	3537.5 	0.89
> P78344_and_P62945 	0.6290067873741413 	0.671387 	0.06515304551943633 	17.472288744790212 	34.442784810126575 	-24469.558976366974 	B_C 	15 	0.333 	0.133 	0.533 	18 	0.365 	2 	19 	2.23 	1212.56 	-0.33
> P78344_and_P09132 	0.6211262691675556 	0.6589203 	0.08134475366649119 	10.510612529080088 	66.92890109890108 	-28394.159764210377 	B_C 	9 	0.111 	0.556 	0.333 	6 	0.388 	7 	13 	3.48 	765.08 	-0.49
> P78344_and_P22090 	0.5515223939913818 	0.59033155 	0.14460282477765915 	20.55140308838386 	58.60125000000003 	-15654.731419052754 	B_C 	27 	0.296 	0.259 	0.407 	30 	0.418 	8 	11 	-0.2 	1471.83 	-0.87
> P78344_and_O76094 	0.5169412161606898 	0.5467848 	0.2130915592329316 	23.06159787928253 	45.59938144329897 	-65640.10889856739 	B_C 	139 	0.309 	0.252 	0.288 	218 	0.226 	46 	11 	-31.67 	4363.1 	0.56
> P78344_and_Q9NX20 	0.36620426396535577 	0.35568807 	0.20392021331888244 	19.932819245505506 	63.48367816091956 	-34954.06917864921 	B_C 	46 	0.239 	0.217 	0.326 	69 	0.095 	15 	10 	-2.43 	1540.74 	-0.77
> P78344_and_P23588 	0.34902449646950484 	0.34881938 	0.1385904745097395 	15.125836796890884 	43.50447826086955 	-24956.307968167053 	B_C 	50 	0.3 	0.4 	0.2 	51 	0.521 	9 	9 	-23.48 	2401.89 	1.28
> P78344_and_P61011 	0.33512340677145236 	0.32496715 	0.3353651779084972 	25.146222874294363 	60.29734693877547 	-23965.434001309848 	B_C 	85 	0.294 	0.388 	0.118 	133 	0.194 	17 	5 	-10.47 	2421.55 	0.57
> P78344_and_P08240 	0.21724664073114736 	0.18381809 	0.31321204279729065 	28.314014073117495 	62.73298113207545 	-110237.89718595374 	B_C 	63 	0.222 	0.365 	0.317 	86 	0.191 	14 	9 	-6.76 	2537.77 	-0.49
> P78344_and_Q9Y5M8 	0.22085763865889452 	0.1837084 	0.4620402338477464 	26.252773164644122 	76.23718309859156 	-50507.42865413394 	B_C 	53 	0.189 	0.377 	0.34 	78 	0.079 	17 	4 	-7.3 	1403.33 	-0.22
> 
> Perhaps you could try again but use a cutoff value of 100? Yours Dingquan

Hey @dingquanyu 
I tried it with that cutoff value, also to no avail. Don't think anything was cached, as I used the new .sif file and ran the command from [feature 2](https://github.com/KosinskiLab/AlphaPulldown/blob/main/manuals/example_1.md#3rd-step-evaluation-and-visualisation) which uses this image directly. 
For further clarification, I run that command on the output acquired from step 2 (predicting of the structures). In my case (see image and error message from earlier), on APD_out2 which contains the folders with the prediction files.
![image](https://github.com/KosinskiLab/AlphaPulldown/assets/118811684/4cdbad91-751f-4047-b743-9c6fa9e7963b)

Thanks for the help!

**Comment by dingquanyu** [comment]
@B0r1sD Thanks for the update. Could you show me the full singularity command you have run? I guess you might have mounted a wrong directory. Based on your screenshot, the correct mount is: ```--bind testing_APD_module/APD_out2:/mnt``` Maybe you mounted ```--bind testing_APD_module/APD_out2/P78344_and_O76094:/mnt``` instead? If so, then the singularity will report no structure has satisfied the cutoff, no matter how high the cutoff is. 

Yours
Dingquan

**Comment by B0r1sD** [comment]
> @B0r1sD Thanks for the update. Could you show me the full singularity command you have run? I guess you might have mounted a wrong directory. Based on your screenshot, the correct mount is: `--bind testing_APD_module/APD_out2:/mnt` Maybe you mounted `--bind testing_APD_module/APD_out2/P78344_and_O76094:/mnt` instead? If so, then the singularity will report no structure has satisfied the cutoff, no matter how high the cutoff is.
> 
> Yours Dingquan

No, as seen in my first example from above. I mount the folder which contains the folders. Maybe others from this thread can try it out to see if it works for them? I'll definitely check again next week to be sure. Thanks if possible @polya18 @krafie @maxvdb-dev !

**Comment by B0r1sD** [comment]
I finally was able to get the `predictions_with_good_interpae.csv` file thanks to the newest alpha-analysis.sif singularity file (2.0.0 beta v3). However, I applied this on output from APD v1.0.4 so it might not be completely accurate as per the release notes:
> If you have created models using the versions prior to the  alphapulldown==2.0.0b3, please rerun the run_multimer_jobs.py before using the updated the singularity image. The rerun will be quick as only the result pickles are to be changed.

But some feedback, Singularities' `--nv` option is now needed in order to use the GPU, otherwise you get the error:
> Unable to initialize backend 'cuda': FAILED_PRECONDITION: No visible GPU devices.

Command ran for feature 2: 
```sh
singularity exec --nv --no-home --bind /path/to/APD_OUT2:/mnt /path/to/alpha-analysis.sif run_get_good_pae.sh --output_dir=/mnt --cutoff=10
```

Ping @dingquanyu
