### ISSUE TITLE
Error on convert_to_modelcif.py:222 while running run_multimer_jobs.py

### ISSUE THREAD

**Issue by KmyMF** [KosinskiLab/AlphaPulldown#508]
Hi,

I'm having an issue while running run_multimer_jobs.py in a cluster. The script was able to generate the files of the protein interaction predictions, including CIF files, but it didn't complete the job. Instead, "ends" with Failed, Mixed, ExitCode [0-1] and generates several sub-jobs that also "end" with this Failed, Mixed, ExitCode [0-1] message and resubmission. I say end in quotes because it never ends, and it resubmits new sub-jobs eternally without completing the job. The log files show the predictions are complete, but this error appears after `Converting to ModelCIF format..`
```
Error:
/hb/home/cmoral44/.conda/envs/AlphaPulldown2/lib/python3.11/site-packages/alphapulldown/scripts/convert_to_modelcif.py:222:
UserWarning: LocalPairwiseQAScoresFile is deprecated. Use QAMetricsFile
instead.
```

 I had to put my job on hold because it was creating sub-jobs non-stop and taking all the cluster resources. I'm not sure why it is not completing the job if all the output files are complete. I appreciate some input on what I can do.

Thanks

Camila

**Comment by DimaMolod** [comment]
Hi @KmyMF
I think you are using the old version of the AlphaPulldown, because this issue was resolved in this commit https://github.com/KosinskiLab/AlphaPulldown/commit/4baca881b4cdb354d24c6ab583f8a3e118ef59e0
What version are you using? Could you update to the latest version and try again?
Best,
Dima

**Comment by KmyMF** [comment]
I have version 2.0.3. I installed with `python3 -m pip install alphapulldown` 

```
(AlphaPulldown2) [cmoral44@hb-login ~]$ pip show alphapulldown
Name: alphapulldown
Version: 2.0.3
Summary: Pipeline allows massive screening using alphafold
Home-page: https://github.com/KosinskiLab/AlphaPulldown
Author: EMBL Hamburg
Author-email: alphapulldown@embl-hamburg.de
License:
Location: /hb/home/cmoral44/.conda/envs/AlphaPulldown2/lib/python3.11/site-packages
Requires: absl-py, appdirs, biopython, chex, dm-haiku, dm-tree, h5py, immutabledict, importlib-metadata, importlib-resources, ipython, ipywidgets, jupyterlab, matplotlib, ml-collections, ml-dtypes, nbformat, pandas, py3Dmol, pytest, setuptools, tensorflow-cpu, tqdm
Required-by:
```

**Comment by DimaMolod** [comment]
You are right, sorry - I committed this fix after we released 2.0.3. 
You can either install the latest version from the main branch:
`git clone https://github.com/KosinskiLab/AlphaPulldown.git` 
`cd AlphaPulldown`
`pip install .`
or wait for the next week when I merge other changes and release 2.0.4
Sorry for the inconveniences,
Dima

**Comment by KmyMF** [comment]
Thanks! I updated it and am running a test now!

**Comment by KmyMF** [comment]
HI! The installation from the main branch resolved the convert_to_modelcif problem. But I'm still getting the issue of the resubmission. Even if the first job is completed and the predictions made, the script continuously resubmits new jobs. On the completed job, I can see these errors:

```
2025-05-01 22:22:48.132176: W external/xla/xla/stream_executor/cuda/cuda_command_buffer.cc:668] Retry CUDA graph instantiation after OOM error
E0501 22:22:48.133938 1546900 pjrt_stream_executor_client.cc:3077] Execution of replica 0 failed: RESOURCE_EXHAUSTED: Underlying backend ran out of memory trying to instantiate graph with 355 nodes and 0 conditionals (total of 77 alive graphs in the process). You can try to (a) Give more memory to the driver by reducing XLA_CLIENT_MEM_FRACTION (b) Disable command buffers with 'XLA_FLAGS=--xla_gpu_enable_command_buffer=' (empty set). Original error: Failed to instantiate CUDA graph: CUDA_ERROR_OUT_OF_MEMORY: out of memory
Traceback (most recent call last):
  File "/hb/home/cmoral44/.conda/envs/AlphaPulldown2/bin/run_structure_prediction.py", line 369, in <module>
    app.run(main)
  File "/hb/home/cmoral44/.conda/envs/AlphaPulldown2/lib/python3.11/site-packages/absl/app.py", line 316, in run
    _run_main(main, args)
  File "/hb/home/cmoral44/.conda/envs/AlphaPulldown2/lib/python3.11/site-packages/absl/app.py", line 261, in _run_main
    sys.exit(main(argv))
             ^^^^^^^^^^
  File "/hb/home/cmoral44/.conda/envs/AlphaPulldown2/bin/run_structure_prediction.py", line 356, in main
    predict_structure(
  File "/hb/home/cmoral44/.conda/envs/AlphaPulldown2/bin/run_structure_prediction.py", line 207, in predict_structure
    for predicted_job in predicted_jobs:
  File "/hb/home/cmoral44/.conda/envs/AlphaPulldown2/lib/python3.11/site-packages/alphapulldown/folding_backend/alphafold_backend.py", line 437, in predict
    prediction_results = AlphaFoldBackend.predict_individual_job(
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/hb/home/cmoral44/.conda/envs/AlphaPulldown2/lib/python3.11/site-packages/alphapulldown/folding_backend/alphafold_backend.py", line 388, in predict_individual_job
    prediction_result = model_runner.predict(
                        ^^^^^^^^^^^^^^^^^^^^^
  File "/hb/home/cmoral44/.conda/envs/AlphaPulldown2/lib/python3.11/site-packages/alphafold/model/model.py", line 167, in predict
    result = self.apply(self.params, jax.random.PRNGKey(random_seed), feat)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: RESOURCE_EXHAUSTED: Underlying backend ran out of memory trying to instantiate graph with 355 nodes and 0 conditionals (total of 77 alive graphs in the process). You can try to (a) Give more memory to the driver by reducing XLA_CLIENT_MEM_FRACTION (b) Disable command buffers with 'XLA_FLAGS=--xla_gpu_enable_command_buffer=' (empty set). Original error: Failed to instantiate CUDA graph: CUDA_ERROR_OUT_OF_MEMORY: out of memory
Traceback (most recent call last):
  File "/hb/home/cmoral44/.conda/envs/AlphaPulldown2/bin/run_multimer_jobs.py", line 147, in <module>
    app.run(main)
  File "/hb/home/cmoral44/.conda/envs/AlphaPulldown2/lib/python3.11/site-packages/absl/app.py", line 316, in run
    _run_main(main, args)
  File "/hb/home/cmoral44/.conda/envs/AlphaPulldown2/lib/python3.11/site-packages/absl/app.py", line 261, in _run_main
    sys.exit(main(argv))
             ^^^^^^^^^^
  File "/hb/home/cmoral44/.conda/envs/AlphaPulldown2/bin/run_multimer_jobs.py", line 143, in main
    subprocess.run(" ".join(command), check=True, shell=True)
  File "/hb/home/cmoral44/.conda/envs/AlphaPulldown2/lib/python3.11/subprocess.py", line 569, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command 'python3 /hb/home/cmoral44/.conda/envs/AlphaPulldown2/bin/run_structure_prediction.py --output_directory /hb/home/cmoral44/predictions_output_test --num_cycle 1 --num_predictions_per_model 2 --data_directory /hb/home/cmoral44/params --features_directory /hb/home/cmoral44/features_output --pair_msa  --nomsa_depth_scan  --nomultimeric_template  --fold_backend alphafold --nocompress_result_pickles  --noremove_result_pickles  --remove_keys_from_pickles  --use_ap_style  --use_gpu_relax  --protein_delimiter + --models_to_relax None --input NP_571032.2+NP_571032.2' returned non-zero exit status 1. 
```

For reference, I'm using 2 nodes, 4 CPU cores, and 30 GB per task, but at the end of the job, it says it only used 1 CPU core and 18 GB. So I'm not sure if I should dedicate more memory to the job, or if this error has nothing to do with that. What is the recommended?

Also, I'm really not sure why I'm resubmitting if the output files of the predictions are complete. Can I just cancel these resubmissions and use the files as they are?

Thanks

Camila

**Comment by DimaMolod** [comment]
Hey Camila,

what is actually happening is a GPU OOM error triggered when XLA tries to instantiate a CUDA graph. So, `run_multimer_jobs.py` exits with non-zero status when the predict script runs, so the job scheduler thinks it failed and requeues it. I suggest doing exactly what your log recommends: try disabling command buffers by setting `XLA_FLAGS=--xla_gpu_enable_command_buffer=`. That usually resolves this kind of CUDA graph memory error. You can also reduce memory usage by lowering XLA_PYTHON_CLIENT_MEM_FRACTION if needed. And yes, if the output files look complete, it’s safe to cancel the resubmissions—the script just keeps retrying because it exits with an error code when it runs out of memory. But I suggest using GPUs for predictions as it is significantly faster.
I am closing this issue as your original problem with modelcif was resolved, please feel free to open a new one if needed.

Cheers
Dima
